apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: exq2za2f1-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/exq2za2f1-java-springboot-gitops